# -*- coding: utf-8 -*-
"""Guessing Game.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1W4rhDlQHndLhaOfW--qUvPhLY4wQXmKq
"""

import random
secret_num = random.randint(1,100)
guess_num = int(input("Enter a number between 1 and 100: "))
c=1
won=False
while(guess_num!=secret_num):
  c+=1
  if(c==10):
    print(f"Oopsie Woopsie, ten chances gone,{secret_num} is the secret number")
    break
  if(guess_num>secret_num + 25):
    print("Way too High")
  elif(guess_num>secret_num + 10):
    print("Too High")
  elif(guess_num<secret_num - 25):
    print("Way too Low")
  elif(guess_num<secret_num -10):
    print("Too Low")
  elif(guess_num>secret_num):
    print("Nearly There! go lower")
  elif(guess_num<secret_num):
    print("Nearly There! go higher")

  if(guess_num!=secret_num):
    guess_num = int(input("Guess again: "))

  if(guess_num==secret_num):
    won=True

if won:
  print(f"To get the secret number {secret_num} you took {c} attempts")
else:
  print("Better Luck Next time")

